=== paulushub/SandAssists/Main/Source/Resources/Schemas/ConceptualContent.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="conceptualContent">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="categories" type="categoriesType" minOccurs="0" maxOccurs="1">
                </xs:element>
                <xs:element name="properties" type="propertiesType" minOccurs="0" maxOccurs="1">
                </xs:element>
                <xs:element name="items" type="itemsType" maxOccurs="1" minOccurs="1">
                </xs:element>
            </xs:sequence>
            <xs:attribute name="version" type="xs:float" use="required" />
        </xs:complexType>
        <!--Make the key of each property tag unique -->
        <xs:unique name="property">
            <xs:selector xpath="*/property" />
            <xs:field xpath="@key" />
        </xs:unique>
        <!--Make the id of each item tag unique -->
        <xs:unique name="item">
            <xs:selector xpath=".//item" />
            <xs:field xpath="@id" />
        </xs:unique>
    </xs:element>
    <xs:complexType name="categoriesType">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="category">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:ID" use="required" />
                    <xs:attribute name="description" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="propertiesType">
        <xs:sequence>
            <xs:element name="property" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="key" type="xs:string" use="required" />
                    <xs:attribute name="value" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="itemsType">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="item" type="itemType" minOccurs="0">
            </xs:element>
        </xs:sequence>
        <xs:attribute name="default" type="guidType" use="optional" />
    </xs:complexType>
    <xs:complexType name="itemType">
        <xs:sequence>
            <xs:element name="title" type="xs:string" maxOccurs="1" minOccurs="1" />
            <xs:element name="path" minOccurs="1" maxOccurs="1" type="pathType">
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="item" type="itemType">
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="guidType" use="required" />
        <xs:attribute name="isNew" type="xs:boolean" use="required" />
        <xs:attribute name="visible" type="xs:boolean" use="required" />
        <xs:attribute name="revision" type="xs:unsignedShort" use="required" />
    </xs:complexType>
    <xs:complexType name="pathType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="include" type="xs:IDREFS" use="optional" />
                <xs:attribute name="format" type="formatType" use="optional" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="guidType">
        <xs:restriction base="xs:string">
            <xs:pattern value="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="formatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="None" />
            <xs:enumeration value="MamlDoc" />
            <xs:enumeration value="HtmlDoc" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== paulushub/SandAssists/Main/Sandcastle/Builders/Schemas/ConceptualContentSample.xml
<?xml version="1.0" encoding="utf-8"?>
<conceptualContent version="1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ConceptualContent.xsd">
    <categories>
        <category name="catId1" description="Express Edition"/>
        <category name="catId2" description="Standard Edition"/>
        <category name="catId3" description="Professional Edition"/>
        <category name="catId4" description="Enterprise Edition"/>
        <category name="catId5" description="Trial Edition"/>
        <category name="catId6" description="Windows Version"/>
        <category name="catId7" description="ASP.NET Version"/>
    </categories>
    <properties>
        <!-- Copy the image folder to the output folder for user image links -->
        <property key="$Copy$" value="Image:Output\Image"/>
        <property key="$Move$" value="Art:Output\Image"/>
    </properties>
    <items default="2aca5da4-6f94-43a0-9817-5f413d16f100">
        <item id="2aca5da4-6f94-43a0-9817-5f413d16f100" isNew="false" visible="true" revision="1">
            <title>Sandcastle For .NET</title>
            <path include="catId1 catId3" format="MamlDoc">Sandcastle.xml</path>
        </item>
        <item id="2aca5da4-6f94-43a0-9817-5f413d16f101" isNew="true" visible="true" revision="1">
            <title>What is New</title>
            <path include="catId1 catId3 catId6">WhatsNew.xml</path>
        </item>
        <item id="2aca5da4-6f94-43a0-9817-5f413d16f102" isNew="false" visible="true" revision="1">
            <title>Suports</title>
            <path include="catId1 catId3">Supports.xml</path>
        </item>
        <item id="2aca5da4-6f94-43a0-9817-5f413d16f103" isNew="false" visible="true" revision="1">
            <title>Introduction</title>
            <path include="">Introduction\Introduction.xml</path>
            <item id="2aca5da4-6f94-43a0-9817-5f413d16f104" isNew="false" visible="true" revision="1">
                <title>Installations and Requirements</title>
                <path include="catId1 catId2">Introduction\Installation.xml</path>
            </item>
            <item id="2aca5da4-6f94-43a0-9817-5f413d16f105" isNew="false" visible="true" revision="1">
                <title>Features List</title>
                <path include="catId1 catId2">Introduction\Features.xml</path>
            </item>
            <item id="2aca5da4-6f94-43a0-9817-5f413d16f106" isNew="false" visible="true" revision="1">
                <title>Compare Editions</title>
                <path>Introduction\Editions.xml</path>
                <item id="2aca5da4-6f94-43a0-9817-5f413d16f107" isNew="false" visible="true" revision="1">
                    <title>Installations and Requirements</title>
                    <path include="catId1 catId2">Introduction\Other\Installation.xml</path>
                </item>
                <item id="2aca5da4-6f94-43a0-9817-5f413d16f108" isNew="false" visible="true" revision="1">
                    <title>Features List</title>
                    <path include="catId1 catId2">Introduction\Other\Features.xml</path>
                </item>
            </item>
        </item>
    </items>
</conceptualContent>
