=== paulushub/SandAssists/Main/Sandcastle/Builders/Schemas/MediaArts.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>
            This schema describes the media stock file used by the Microsoft's
            Sandcastle Help Compiler to resolve links to images embedded in the
            conceptual help documents.
        </xs:documentation>
    </xs:annotation>
    <!-- 
        This is the root name of the shared media stock.
        The official name is not published, but any name could be used.
        
        The following illustrates its use:
        
        1. In the Sandcastle stock media file:
        
        <?xml version="1.0" encoding="utf-8"?>
        <mediaArts id="7aca5da4-6f94-43a0-9817-5f413d16f000"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="MediaArts.xsd">
            
            <item id="7aca5da4-6f94-43a0-9817-5f413d16f001">
                <image file="demo.jpg">
                    <altText>A demo application</altText>
                </image>
            </item>   
            
            <item id="...">
                ...
            </item>
            
        </mediaArts>
        
        2. In a Sandcastle document file:  
        
            Link to a stock image as follows:
            
            <mediaLink>
                <image xlink:href="7aca5da4-6f94-43a0-9817-5f413d16f001"/>
            </mediaLink>
  
            Or for inline images...
            
            <mediaLinkInline>
                <image xlink:href="7aca5da4-6f94-43a0-9817-5f413d16f001"/>
            </mediaLinkInline>
    -->
    <xs:element name="mediaArts">
        <xs:annotation>
            <xs:documentation>
                This is the root element for the media stock. In practice, this
                can be of any name since it is not checked by the Sandcastle
                Help Compiler.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="item" type="itemType" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            This specifies a media item target for used in media link.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="guidType" use="required">
                <xs:annotation>
                    <xs:documentation>
                        This is a unique identifier of this shared stock of media.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>

        <!--Make the id of each item tag unique -->
        <xs:unique name="item">
            <xs:selector xpath=".//item" />
            <xs:field xpath="@id" />
        </xs:unique>
    </xs:element>
    <!--
        This defines a simple type for GUID, so that we could 
        validate identifiers.
    -->
    <xs:simpleType name="guidType">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                The representation of a GUID, generally the id of an element.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$" />
        </xs:restriction>
    </xs:simpleType>
    <!--
        This provides the information on the image of the link.
    -->
    <xs:complexType name="imageType">
        <xs:annotation>
            <xs:documentation>
                This defines the image information for a media item link.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="altText" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        The text to be displayed if the image is not found.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="file" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>
                    The actual name of the file, including the file extension.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <!--
        This defines each item in the shared media stock.
    -->
    <xs:complexType name="itemType">
        <xs:annotation>
            <xs:documentation>
                This defines a media item target for used in media link.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="image" nillable="false" type="imageType">
                <xs:annotation>
                    <xs:documentation>
                        This specifies the image information for a media link.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="guidType" use="required">
            <xs:annotation>
                <xs:documentation>
                    This unique identifier is used to provide link 
                    in the document to the image of this item.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== paulushub/SandAssists/Main/Source/Resources/Schemas/MediaArtsSample.xml
<?xml version="1.0" encoding="utf-8"?>
<mediaArts id="3aca5da4-6f94-43a0-9817-5f413d16f000"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="MediaArts.xsd">  
    <item id="3aca5da4-6f94-43a0-9817-5f413d16f100">
        <image file="SmallArrow.gif">
            <altText>A Small Arrow</altText>
        </image>
    </item>
    <item id="3aca5da4-6f94-43a0-9817-5f413d16f101">
        <image file="ArrowNormal.png">
            <altText>Arrow Normal</altText>
        </image>
    </item>
    <item id="3aca5da4-6f94-43a0-9817-5f413d16f110">
        <image file="Warning.png">
            <altText>Warming</altText>
        </image>
    </item>
    <item id="3aca5da4-6f94-43a0-9817-5f413d16f112">
        <image file="SmallWarning.png">
            <altText>Warming</altText>
        </image>
    </item>
    <item id="3aca5da4-6f94-43a0-9817-5f413d16f113">
        <image file="Information.png">
            <altText>Information</altText>
        </image>
    </item>
    <item id="3aca5da4-6f94-43a0-9817-5f413d16f114">
        <image file="Question.png">
            <altText>Question</altText>
        </image>
    </item>
    <item id="3aca5da4-6f94-43a0-9817-5f413d16f115">
        <image file="Error.png">
            <altText>Error</altText>
        </image>
    </item>
</mediaArts>
